# Generated by Django 5.1 on 2025-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("organization_name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("is_responded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DashboardAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_vulnerabilities", models.IntegerField(default=0)),
                ("total_projects", models.IntegerField(default=0)),
                ("dast_coverage", models.IntegerField(default=0)),
                ("risk_score", models.IntegerField(default=0)),
                ("vulnerability_trend", models.TextField(blank=True, default="")),
                (
                    "vulnerability_distribution",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "weekly_vulnerability_trend",
                    models.TextField(blank=True, default=""),
                ),
                ("project_security_analysis", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DynamicAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dynamic_analysis_type",
                    models.CharField(
                        choices=[("Nuclei", "Nuclei")], default="Nuclei", max_length=50
                    ),
                ),
                ("source_url", models.URLField()),
                ("Nuclei_analysis_result", models.URLField(null=True)),
                (
                    "dynamic_analysis_status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Cloning", "Cloning"),
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Waiting",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EarlyAccessUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_allowed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.CharField(max_length=50)),
                ("notification_subject", models.CharField(max_length=180)),
                ("notification_description", models.TextField()),
                (
                    "notification_status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Open",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Success", "Success"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Card", "Card"),
                            ("UPI", "UPI"),
                            ("Net Banking", "Net Banking"),
                        ],
                        default="Card",
                        max_length=50,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("payment_expiry", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricing_plan", models.CharField(max_length=50)),
                ("pricing_description", models.TextField()),
                ("pricing_features", models.JSONField(default=dict)),
                ("pricing_offer", models.CharField(max_length=50)),
                (
                    "pricing_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pricing_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=50)),
                ("project_description", models.TextField()),
                ("project_type", models.CharField(max_length=50)),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                            ("On Hold", "On Hold"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("project_url", models.URLField(null=True)),
                (
                    "project_logo",
                    models.ImageField(null=True, upload_to="project_logo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_url", models.URLField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                ("alert_short_description", models.CharField(max_length=180)),
                ("alert_detailed_description", models.TextField()),
                ("source", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Low",
                        max_length=50,
                    ),
                ),
                (
                    "alert_status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Investigating", "Investigating"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_name", models.CharField(max_length=100)),
                ("policy_description", models.TextField()),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Low",
                        max_length=50,
                    ),
                ),
                (
                    "policy_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Under Review", "Under Review"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("standard", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StaticAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "static_analysis_type",
                    models.CharField(
                        choices=[
                            ("LLM", "LLM"),
                            ("GitLeaks", "GitLeaks"),
                            ("CVEscan", "CVEscan"),
                        ],
                        default="LLM",
                        max_length=50,
                    ),
                ),
                ("source_url", models.URLField()),
                ("LLM_analysis_result", models.URLField(null=True)),
                ("CVEscan_analysis_result", models.URLField(null=True)),
                ("GitLeaks_analysis_result", models.URLField(null=True)),
                ("repo_folder_name", models.TextField(blank=True, default="")),
                (
                    "static_analysis_status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Cloning", "Cloning"),
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Waiting",
                        max_length=50,
                    ),
                ),
                ("analysis_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_start_date", models.DateTimeField(auto_now_add=True)),
                ("subscription_end_date", models.DateTimeField(auto_now=True)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SupportChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_subject", models.CharField(max_length=180)),
                ("chat_description", models.TextField()),
                ("chat_content", models.JSONField(default=dict)),
                (
                    "chat_status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Open",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_type", models.CharField(max_length=50)),
                ("ticket_subject", models.CharField(max_length=180)),
                ("ticket_description", models.TextField()),
                (
                    "ticket_status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Open",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "testing_type",
                    models.CharField(
                        choices=[
                            ("LLM", "LLM"),
                            ("GitLeaks", "GitLeaks"),
                            ("Nuclei", "Nuclei"),
                            ("CVEscan", "CVEscan"),
                        ],
                        default="LLM",
                        max_length=50,
                    ),
                ),
                ("source_url", models.URLField()),
                ("LLM_test_result", models.URLField(null=True)),
                ("CVEscan_test_result", models.URLField(null=True)),
                ("GitLeaks_test_result", models.URLField(null=True)),
                ("Nuclei_test_result", models.URLField(null=True)),
                ("repo_folder_name", models.TextField(blank=True, default="")),
                (
                    "testing_status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Cloning", "Cloning"),
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Waiting",
                        max_length=50,
                    ),
                ),
                ("test_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VulnerabilityAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("critical_vulnerabilities", models.IntegerField(default=0)),
                ("high_vulnerabilities", models.IntegerField(default=0)),
                ("medium_vulnerabilities", models.IntegerField(default=0)),
                ("low_vulnerabilities", models.IntegerField(default=0)),
                ("risk_assessment_matrix", models.TextField(blank=True, default="")),
                ("vul_trend_by_severity", models.TextField(blank=True, default="")),
                ("severity_distribution", models.TextField(blank=True, default="")),
                ("vul_timeline", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
