# Generated by Django 5.1 on 2025-10-02 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("authenticate", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardanalytics",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="dashboardanalytics",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dynamicanalysis",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="dynamicanalysis",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="securityalert",
            name="alert_assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityalert",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="securityalert",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="securityalert",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="staticanalysis",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="staticanalysis",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pricing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.pricingplan"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.subscription"
            ),
        ),
        migrations.AddField(
            model_name="supportchat",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="supportchat",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="supportchat",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="testing",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="testing",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilityanalysis",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilityanalysis",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilityanalysis",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
