# Generated by Django 5.1 on 2025-11-30 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "app_type",
                    models.CharField(
                        choices=[("APK", "APK"), ("IPA", "IPA")],
                        default="APK",
                        max_length=10,
                    ),
                ),
                ("app_file", models.FileField(upload_to="mobile_apps/")),
                ("file_size", models.BigIntegerField(default=0)),
                ("analysis_result", models.URLField(blank=True, null=True)),
                (
                    "mobile_app_analysis_status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Uploading", "Uploading"),
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Waiting",
                        max_length=50,
                    ),
                ),
                ("total_vulnerabilities", models.IntegerField(default=0)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.project"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile App Analysis",
                "verbose_name_plural": "Mobile App Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
