# Generated by Django 5.1 on 2025-11-30 15:20

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing records"""
    StaticAnalysis = apps.get_model('api', 'StaticAnalysis')
    DynamicAnalysis = apps.get_model('api', 'DynamicAnalysis')
    MobileAppAnalysis = apps.get_model('api', 'MobileAppAnalysis')
    
    for record in StaticAnalysis.objects.all():
        record.scan_uuid = uuid.uuid4()
        record.save(update_fields=['scan_uuid'])
    
    for record in DynamicAnalysis.objects.all():
        record.scan_uuid = uuid.uuid4()
        record.save(update_fields=['scan_uuid'])
    
    for record in MobileAppAnalysis.objects.all():
        record.scan_uuid = uuid.uuid4()
        record.save(update_fields=['scan_uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_add_mobile_app_analysis_fields"),
    ]

    operations = [
        # Step 1: Add fields WITHOUT unique constraint
        migrations.AddField(
            model_name="dynamicanalysis",
            name="scan_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mobileappanalysis",
            name="scan_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staticanalysis",
            name="scan_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
            ),
        ),
        # Step 2: Generate unique UUIDs for existing records
        migrations.RunPython(generate_unique_uuids, reverse_code=migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="dynamicanalysis",
            name="scan_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="mobileappanalysis",
            name="scan_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="staticanalysis",
            name="scan_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
    ]
