# Generated by Django 5.1 on 2025-11-30 15:35

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing Report records"""
    Report = apps.get_model('api', 'Report')
    
    for record in Report.objects.all():
        record.report_uuid = uuid.uuid4()
        record.save(update_fields=['report_uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_add_scan_uuid_fields"),
    ]

    operations = [
        # Step 1: Add field WITHOUT unique constraint
        migrations.AddField(
            model_name="report",
            name="report_uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        # Step 2: Generate unique UUIDs for existing records
        migrations.RunPython(generate_unique_uuids, reverse_code=migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="report",
            name="report_uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
