# Generated by Django 5.1 on 2025-11-30 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_add_report_uuid_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserExtensionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "extension_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "extension_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "extension_type",
                    models.CharField(
                        choices=[
                            ("CRX", "Chrome Extension (.crx)"),
                            ("XPI", "Firefox Extension (.xpi)"),
                            ("SAFARIEXTZ", "Safari Extension (.safariextz)"),
                            ("ZIP", "Generic Extension (.zip)"),
                        ],
                        default="CRX",
                        max_length=15,
                    ),
                ),
                ("extension_file", models.FileField(upload_to="browser_extensions/")),
                ("file_size", models.BigIntegerField(default=0)),
                ("manifest_version", models.IntegerField(blank=True, null=True)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("analysis_result", models.URLField(blank=True, null=True)),
                (
                    "browser_extension_analysis_status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Uploading", "Uploading"),
                            ("Extracting", "Extracting"),
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Waiting",
                        max_length=50,
                    ),
                ),
                ("total_vulnerabilities", models.IntegerField(default=0)),
                ("code_vulnerabilities", models.IntegerField(default=0)),
                ("permission_issues", models.IntegerField(default=0)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("risk_score", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.project"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Browser Extension Analysis",
                "verbose_name_plural": "Browser Extension Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
