# Generated by Django 5.1 on 2026-07-10 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_browser_extension_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SCAAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('source_url', models.URLField()),
                ('sca_analysis_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Cloning', 'Cloning'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Waiting', max_length=50)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('total_dependencies', models.IntegerField(default=0)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('code_vulnerabilities', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SCA Analysis',
                'verbose_name_plural': 'SCA Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
