# Generated by Django 5.1 on 2026-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scaanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaanalysis',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='sca_uploads/'),
        ),
        migrations.AddField(
            model_name='scaanalysis',
            name='source_type',
            field=models.CharField(choices=[('github', 'GitHub URL'), ('upload', 'Uploaded Archive')], default='github', max_length=10),
        ),
        migrations.AlterField(
            model_name='scaanalysis',
            name='sca_analysis_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Cloning', 'Cloning'), ('Extracting', 'Extracting'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='scaanalysis',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
