# Generated by Django 5.1 on 2026-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_staticanalysis_taint_analysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticanalysis',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='sast_uploads/'),
        ),
        migrations.AddField(
            model_name='staticanalysis',
            name='source_type',
            field=models.CharField(choices=[('github', 'GitHub URL'), ('upload', 'Uploaded Archive')], default='github', max_length=10),
        ),
        migrations.AlterField(
            model_name='staticanalysis',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
