# Generated by Django 5.1 on 2026-07-11 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_staticanalysis_source_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SASTTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('false_positive', 'False Positive'), ('accepted_risk', 'Accepted Risk'), ('wont_fix', "Won't Fix")], default='open', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('cwe', models.CharField(blank=True, default='', max_length=20)),
                ('sink', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sast_triage', to='api.project')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('project', 'fingerprint')},
            },
        ),
    ]
