# Generated by Django 5.1 on 2026-06-20 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scan_type', models.CharField(choices=[('domain', 'Domain Pipeline'), ('xss', 'XSS (dalfox)'), ('sqli', 'SQL Injection (sqlmap)'), ('fuzz', 'Fuzzing (ffuf)'), ('jwt', 'JWT Analysis'), ('github', 'GitHub Recon'), ('mobile', 'Mobile App (MobSF)'), ('aem', 'Adobe AEM'), ('depconf', 'Dependency Confusion'), ('monitor', 'Monitoring Daemon')], default='domain', max_length=20)),
                ('target', models.CharField(help_text='Domain, URL, repo, or file identifier', max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial (some steps skipped/failed)')], default='queued', max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('total_findings', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='', help_text='AI/auto-generated summary')),
                ('summary_url', models.URLField(blank=True, help_text='R2 link to full summary report', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=0)),
                ('step_key', models.CharField(max_length=64)),
                ('tool', models.CharField(default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('empty', 'Empty'), ('skipped', 'Skipped (tool missing/disabled)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('record_count', models.IntegerField(default=0)),
                ('output_url', models.URLField(blank=True, null=True)),
                ('output_s3_uri', models.CharField(blank=True, default='', max_length=500)),
                ('command', models.TextField(blank=True, default='')),
                ('duration_s', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recon.scanrun')),
            ],
            options={
                'ordering': ['run', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('subdomain', 'Subdomain'), ('live_host', 'Live Host'), ('port', 'Open Port'), ('tech', 'Technology'), ('takeover', 'DNS Takeover'), ('s3_bucket', 'S3 Bucket'), ('vulnerability', 'Vulnerability'), ('secret', 'Secret/Token'), ('url', 'URL'), ('gf_match', 'GF Pattern Match'), ('backup_file', 'Backup File'), ('misconfig', 'Misconfiguration'), ('other', 'Other')], default='other', max_length=24)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info'), ('unknown', 'Unknown')], default='info', max_length=12)),
                ('title', models.CharField(default='', max_length=300)),
                ('host', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('tool', models.CharField(blank=True, default='', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='recon.scanrun')),
            ],
            options={
                'ordering': ['-severity', 'kind'],
                'indexes': [models.Index(fields=['run', 'kind'], name='recon_findi_run_id_dfa65a_idx'), models.Index(fields=['run', 'severity'], name='recon_findi_run_id_972122_idx')],
            },
        ),
    ]
