# Generated by Django 5.1 on 2026-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='kind',
            field=models.CharField(choices=[('subdomain', 'Subdomain'), ('live_host', 'Live Host'), ('port', 'Open Port'), ('tech', 'Technology'), ('takeover', 'DNS Takeover'), ('s3_bucket', 'S3 Bucket'), ('vulnerability', 'Vulnerability'), ('secret', 'Secret/Token'), ('url', 'URL'), ('gf_match', 'GF Pattern Match'), ('backup_file', 'Backup File'), ('misconfig', 'Misconfiguration'), ('api_endpoint', 'API Endpoint'), ('api_vuln', 'API Vulnerability'), ('other', 'Other')], default='other', max_length=24),
        ),
        migrations.AlterField(
            model_name='scanrun',
            name='scan_type',
            field=models.CharField(choices=[('domain', 'Domain Pipeline'), ('xss', 'XSS (dalfox)'), ('sqli', 'SQL Injection (sqlmap)'), ('fuzz', 'Fuzzing (ffuf)'), ('jwt', 'JWT Analysis'), ('github', 'GitHub Recon'), ('mobile', 'Mobile App (MobSF)'), ('aem', 'Adobe AEM'), ('depconf', 'Dependency Confusion'), ('api', 'API Security (OWASP API Top 10)'), ('monitor', 'Monitoring Daemon')], default='domain', max_length=20),
        ),
    ]
