# Generated by Django 5.1 on 2025-10-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="post_images"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("llm", "LLM"),
                            ("cryptography", "Cryptography"),
                            ("security", "Security"),
                            ("vulnerability", "Vulnerability"),
                            ("exploit", "Exploit"),
                            ("threat", "Threat"),
                            ("attack", "Attack"),
                            ("malware", "Malware"),
                            ("network", "Network"),
                            ("web", "Web"),
                            ("mobile", "Mobile"),
                            ("iot", "IoT"),
                            ("cloud", "Cloud"),
                            ("forensics", "Forensics"),
                            ("cybercrime", "Cybercrime"),
                            ("cyberlaw", "Cyberlaw"),
                            ("cybersecurity", "Cybersecurity"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                ("tags", models.CharField(max_length=100)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("user_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
                    ),
                ),
            ],
        ),
    ]
